language: go
go:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
before_install:
    # install opus
    - wget http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz
    - tar -zxvf opus-1.1.2.tar.gz > /dev/null
    - cd opus-1.1.2
    - ./configure
    - make
    - sudo make install
    - cd ../
install:
    - go get -v .
script:
    - go build